# Generated by Django 4.2.7 on 2023-12-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_orderitem_order_items_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='not delivered', max_length=50),
        ),
    ]
