# Generated by Django 4.2.7 on 2023-12-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.TextField(default='not delivered', max_length=50),
        ),
    ]
