# Generated by Django 4.2.7 on 2023-12-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_order_coupon_info_order_payment_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
