# Generated by Django 4.2.7 on 2024-01-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_orderaddress_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.address'),
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
